title: Sunit Bhopal
logo: /website_code/Sunit_image.png
description: IT Consultant<br>Lake Elsinore,CA(92530)<br>9514638848<br>sunitbhopal@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
#remote_theme: pages-themes/slate@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
